Repository BinaryStudioAcademy/bsa-2021-ats, pull requests merged in 2021-08, with the labels that each got.

#16 Add login markup
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/app/components/app/app.component.html
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/users/components/login-box/login-box.component.html
  frontend/ATS/src/app/users/components/login-box/login-box.component.scss
  frontend/ATS/src/app/users/components/login-box/login-box.component.spec.ts
  frontend/ATS/src/app/users/components/login-box/login-box.component.ts
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.html
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.scss
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.spec.ts
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.ts
  frontend/ATS/src/app/users/components/login/login.component.html
  frontend/ATS/src/app/users/components/login/login.component.scss
  frontend/ATS/src/app/users/components/login/login.component.spec.ts
  frontend/ATS/src/app/users/components/login/login.component.ts
  frontend/ATS/src/app/users/components/logo-block/logo-block.component.html
  frontend/ATS/src/app/users/components/logo-block/logo-block.component.scss
  frontend/ATS/src/app/users/components/logo-block/logo-block.component.spec.ts
  frontend/ATS/src/app/users/components/logo-block/logo-block.component.ts
  frontend/ATS/src/app/users/user-routing.module.ts
  frontend/ATS/src/app/users/users.module.ts
  frontend/ATS/src/assets/images/loginAndRegistrationBackgroundImage.png
  frontend/ATS/src/styles.scss
Labels: UIchange, enhancement

#17 Feature serhiiyanchuk back end authorization
  .env.example/ats_api.env
  backend/src/Application/Application.csproj
  backend/src/Application/Auth/Commands/GenerateAccessTokenCommand.cs
  backend/src/Application/Auth/Commands/LoginCommand.cs
  backend/src/Application/Auth/Commands/LogoutCommand.cs
  backend/src/Application/Auth/Commands/RefreshTokenCommand.cs
  backend/src/Application/Auth/Dtos/AccessTokenDto.cs
  backend/src/Application/Auth/Dtos/AuthUserDto.cs
  backend/src/Application/Auth/Dtos/RefreshTokenDto.cs
  backend/src/Application/Auth/Dtos/RevokeRefreshTokenDto.cs
  backend/src/Application/Auth/Dtos/UserLoginDto.cs
  backend/src/Application/Auth/Exceptions/ExpiredRefreshTokenException.cs
  backend/src/Application/Auth/Exceptions/InvalidTokenException.cs
  backend/src/Application/Auth/Exceptions/InvalidUsernameOrPasswordException.cs
  backend/src/Application/Common/Exceptions/NotFoundException.cs
  backend/src/Application/Interfaces/IJwtService.cs
  backend/src/Application/Interfaces/ISecurityService.cs
  backend/src/Application/Users/Commands/RegisterUserCommand.cs
  backend/src/Application/Users/Dtos/RoleDto.cs
  backend/src/Application/Users/Dtos/UserDto.cs
  backend/src/Application/Users/Dtos/UserRegisterDto.cs
  backend/src/Application/Users/UserProfile.cs
  backend/src/Domain/Common/Auth/AccessToken.cs
  backend/src/Domain/Common/Auth/JwtIssuerOptions.cs
  backend/src/Domain/Domain.csproj
  backend/src/Domain/Interfaces/IRTokenReadRepository.cs
  backend/src/Domain/Interfaces/IReadRepository.cs
  backend/src/Domain/Interfaces/IUserReadRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Abstractions/ReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/RTokenReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/UserReadRepository.cs
  backend/src/Infrastructure/Services/JwtService.cs
  backend/src/Infrastructure/Services/SecurityService.cs
  backend/src/WebAPI/Controllers/ApiController.cs
  backend/src/WebAPI/Controllers/AuthController.cs
  backend/src/WebAPI/Controllers/RegisterController.cs
  backend/src/WebAPI/Controllers/TokenController.cs
  backend/src/WebAPI/Controllers/UsersController.cs
  backend/src/WebAPI/Extensions/ControllerBaseExtensions.cs
  backend/src/WebAPI/Extensions/CorsExtension.cs
  backend/src/WebAPI/Extensions/JwtExtension.cs
  backend/src/WebAPI/Startup.cs
  backend/src/WebAPI/WebAPI.csproj
  backend/src/WebAPI/appsettings.json
Labels: backend api changes, enhancement

#19 Added mail
  .env.example/ats_api.env
  backend/src/Application/Auth/Commands/GenerateAccessTokenCommand.cs
  backend/src/Application/Auth/Commands/LoginCommand.cs
  backend/src/Application/Auth/Commands/LogoutCommand.cs
  backend/src/Application/Auth/Commands/RefreshTokenCommand.cs
  backend/src/Application/Common/Commands/CreateEntityCommand.cs
  backend/src/Application/Common/Commands/DeleteEntityCommand.cs
  backend/src/Application/Common/Commands/UpdateEntityCommand.cs
  backend/src/Application/Common/Mail/MailBodyFactory.cs
  backend/src/Application/Common/Mail/MailSubjectFactory.cs
  backend/src/Application/Common/Queries/GetEntityByIdQuery.cs
  backend/src/Application/Common/Queries/GetEntityListQuery.cs
  backend/src/Application/Interfaces/IMailBuilderService.cs
  backend/src/Application/Interfaces/ISmtp.cs
  backend/src/Application/Interfaces/ISmtpFactory.cs
  backend/src/Application/Mail/SendMailCommand.cs
  backend/src/Application/Users/Commands/Create/CreateUserCommand.cs
  backend/src/Application/Users/Commands/RegisterUserCommand.cs
  backend/src/Application/Users/Queries/GetUserById/GetUserByIdQuery.cs
  backend/src/Domain/Entities/MailTemplate.cs
  backend/src/Domain/Interfaces/Abstractions/IReadRepository.cs
  backend/src/Domain/Interfaces/Abstractions/IWriteRepository.cs
  backend/src/Domain/Interfaces/Read/IMailTemplateReadRepository.cs
  backend/src/Domain/Interfaces/Read/IRTokenReadRepository.cs
  backend/src/Domain/Interfaces/Read/IUserReadRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Mail/GmailSmtpFactory.cs
  backend/src/Infrastructure/Mail/Smtp.cs
  backend/src/Infrastructure/Repositories/Abstractions/MongoReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/MongoWriteRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/ReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/WriteRepository.cs
  backend/src/Infrastructure/Repositories/Read/MailTemplateReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/RTokenReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/UserReadRepository.cs
  backend/src/Infrastructure/Services/MailBuilderService.cs
  backend/src/MailTemplates/default.html
  backend/src/WebAPI/Controllers/UsersController.cs
  backend/src/WebAPI/Properties/example.launchSettings.json
Labels: enhancement

#21 Added multiselect
  frontend/ATS/package-lock.json
  frontend/ATS/package.json
  frontend/ATS/src/app/shared/components/.gitkeep
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.html
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.scss
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/common.scss
  frontend/ATS/tsconfig.json
Labels: enhancement

#24 Implement paging directive
  frontend/ATS/src/app/shared/directives/paginator.directive.scss
  frontend/ATS/src/app/shared/directives/style-paginator.directive.ts
  frontend/ATS/src/styles.scss
Labels: enhancement

#27 Fix mail
  .env.example/ats_api.env
  backend/src/Application/Mail/SendMailCommand.cs
  backend/src/WebAPI/Properties/example.launchSettings.json
Labels: enhancement

#22 Feature irina main layout
  frontend/ATS/package-lock.json
  frontend/ATS/package.json
  frontend/ATS/src/app/app/animations/animation.ts
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/app/components/app/app.component.html
  frontend/ATS/src/app/app/components/app/app.component.scss
  frontend/ATS/src/app/app/components/app/app.component.ts
  frontend/ATS/src/app/app/components/menu/menu.component.html
  frontend/ATS/src/app/app/components/menu/menu.component.scss
  frontend/ATS/src/app/app/components/menu/menu.component.spec.ts
  frontend/ATS/src/app/app/components/menu/menu.component.ts
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/button/button.component.html
  frontend/ATS/src/app/shared/components/button/button.component.scss
  frontend/ATS/src/app/shared/components/button/button.component.spec.ts
  frontend/ATS/src/app/shared/components/button/button.component.ts
  frontend/ATS/src/app/shared/components/header/header.component.html
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/app/shared/components/header/header.component.spec.ts
  frontend/ATS/src/app/shared/components/header/header.component.ts
  frontend/ATS/src/app/shared/components/search-form/search-form.component.html
  frontend/ATS/src/app/shared/components/search-form/search-form.component.scss
  frontend/ATS/src/app/shared/components/search-form/search-form.component.spec.ts
  frontend/ATS/src/app/shared/components/search-form/search-form.component.ts
  frontend/ATS/src/app/shared/services/sidenav.service.spec.ts
  frontend/ATS/src/app/shared/services/sidenav.service.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/vacancies/components/.gitkeep
  frontend/ATS/src/app/vacancies/components/vacancies-list/vacancies-list.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-list/vacancies-list.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-list/vacancies-list.component.spec.ts
  frontend/ATS/src/app/vacancies/components/vacancies-list/vacancies-list.component.ts
  frontend/ATS/src/app/vacancies/vacancies.module.ts
  frontend/ATS/src/app/vacations/vacations.module.ts
  frontend/ATS/src/common.scss
  frontend/ATS/src/styles.scss
Labels: UIchange, enhancement

#23 Added HomePage with Widget component and Vacancy card component and …
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/shared/models/vacancy/vacancy-info.ts
  frontend/ATS/src/app/shared/models/vacancy/vacancy-widget.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/users/components/home/home.component.html
  frontend/ATS/src/app/users/components/home/home.component.scss
  frontend/ATS/src/app/users/components/home/home.component.spec.ts
  frontend/ATS/src/app/users/components/home/home.component.ts
  frontend/ATS/src/app/users/user-routing.module.ts
  frontend/ATS/src/app/users/users.module.ts
  frontend/ATS/src/app/vacancy/vacancy-card/vacancy-card.component.html
  frontend/ATS/src/app/vacancy/vacancy-card/vacancy-card.component.scss
  frontend/ATS/src/app/vacancy/vacancy-card/vacancy-card.component.spec.ts
  frontend/ATS/src/app/vacancy/vacancy-card/vacancy-card.component.ts
  frontend/ATS/src/app/vacancy/vacancy-widget/vacancy-widget.component.html
  frontend/ATS/src/app/vacancy/vacancy-widget/vacancy-widget.component.scss
  frontend/ATS/src/app/vacancy/vacancy-widget/vacancy-widget.component.spec.ts
  frontend/ATS/src/app/vacancy/vacancy-widget/vacancy-widget.component.ts
  frontend/ATS/src/common.scss
  frontend/ATS/src/styles.scss
Labels: enhancement

#25 Add registration markup
  backend/src/Application/Common/Queries/IsEmailAlreadyUsedQuery.cs
  backend/src/Application/Users/Queries/IsEmailAlreadyUsed/IsEmailAlreadyUsedQuery.cs
  backend/src/Domain/Interfaces/Abstractions/IReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/MongoReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/ReadRepository.cs
  backend/src/WebAPI/Controllers/UsersController.cs
  frontend/ATS/src/app/shared/services/notification.service.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.scss
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.ts
  frontend/ATS/src/app/users/components/registration-box/registration-box.component.html
  frontend/ATS/src/app/users/components/registration-box/registration-box.component.scss
  frontend/ATS/src/app/users/components/registration-box/registration-box.component.spec.ts
  frontend/ATS/src/app/users/components/registration-box/registration-box.component.ts
  frontend/ATS/src/app/users/components/registration/registration.component.html
  frontend/ATS/src/app/users/components/registration/registration.component.scss
  frontend/ATS/src/app/users/components/registration/registration.component.spec.ts
  frontend/ATS/src/app/users/components/registration/registration.component.ts
  frontend/ATS/src/app/users/user-routing.module.ts
  frontend/ATS/src/app/users/users.module.ts
  frontend/ATS/src/common.scss
Labels: UIchange, enhancement

#11 Feature ivan hedz elastic search
  .docker/docker-compose.prod.yml
  .docker/docker-compose.services.yml
  .docker/docker-compose.yml
  .env.example/ats_api.env
  backend/src/Application/ApplicantToTags/ApplicantToTagsProfile.cs
  backend/src/Application/ApplicantToTags/CommandQuery/AddTagCommand/AddTagCommand.cs
  backend/src/Application/ApplicantToTags/CommandQuery/DeleteTagCommand/DeleteTagCommand.cs
  backend/src/Application/ApplicantToTags/Commands/CreateApplicantToTagsCommandHandler/CreateApplicantToTagsCommand.cs
  backend/src/Application/ApplicantToTags/Commands/CreateBulkApplicantToTagsCommandHandler/CreateBulkApplicantToTagsCommand.cs
  backend/src/Application/ApplicantToTags/Commands/DeleteApplicantToTagsCommandHandler/DeleteApplicantToTagsCommand.cs
  backend/src/Application/ApplicantToTags/Commands/UpdateApplicantToTagsCommandHandler/UpdateApplicantToTagsCommand.cs
  backend/src/Application/ApplicantToTags/Dtos/ApplicantToTagsDto.cs
  backend/src/Application/ApplicantToTags/Dtos/CreateApplicantToTagsDto.cs
  backend/src/Application/ApplicantToTags/Dtos/TagDto.cs
  backend/src/Application/ApplicantToTags/Dtos/UpdateApplicantToTagsDto.cs
  backend/src/Application/ApplicantToTags/Quaries/GetApplicantToTagsByIdQueryHandler/SearchApplicantToTagsQuery.cs
  backend/src/Application/ApplicantToTags/Quaries/GetApplicantToTagsListBySearchRequestQueryHandler/SearchApplicantToTagsQuery.cs
  backend/src/Application/ApplicantToTags/TagsProfile.cs
  backend/src/Application/Applicants/ApplicantProfile.cs
  backend/src/Application/Applicants/Dtos/ApplicantDto.cs
  backend/src/Application/Applicants/Dtos/CreateApplicantDto.cs
  backend/src/Application/Applicants/Dtos/UpdateApplicantDto.cs
  backend/src/Application/Application.csproj
  backend/src/Application/Common/Commands/CreateBulkElasticDocumentCommand.cs
  backend/src/Application/Common/Commands/CreateElasticDocumentCommand.cs
  backend/src/Application/Common/Commands/DeleteElasticDocumentCommand.cs
  backend/src/Application/Common/Commands/UpdateElasticDocumentCommand.cs
  backend/src/Application/Common/Models/HumanDto.cs
  backend/src/Application/Common/Queries/GetElasticDocumentByIdQuery.cs
  backend/src/Application/Common/Queries/GetElasticDocumentsListSearchRequestQuery.cs
  backend/src/Application/VacancyCandidates/Queries/GetFullByIdQuery.cs
  backend/src/Domain/Entities/Applicant.cs
  backend/src/Domain/Entities/ApplicantToTags.cs
  backend/src/Domain/Entities/Human.cs
  backend/src/Domain/Entities/Tag.cs
  backend/src/Domain/Interfaces/IElasticReadRepository.cs
  backend/src/Domain/Interfaces/IElasticWriteRepository.cs
  backend/src/Infrastructure/Elastic/Seeding/ApplicantToTagsSeeds.cs
  backend/src/Infrastructure/Infrastructure.csproj
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Migrations/20210728131336_BaseModel.cs
  backend/src/Infrastructure/Migrations/20210730101330_AddApplicantIdToVacancyCandidates.cs
  backend/src/Infrastructure/Migrations/20210804155854_ChangeCandidateToStageRelationToM2M.cs
  backend/src/Infrastructure/Repositories/Abstractions/ElasticReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/ElasticWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
  backend/src/WebAPI/Program.cs
  backend/src/WebAPI/Properties/example.launchSettings.json
  backend/src/WebAPI/Startup.cs
Labels: enhancement, backend api changes

#37 Add migration fix
  backend/src/Infrastructure/Migrations/20210728131336_BaseModel.cs
  backend/src/Infrastructure/Migrations/20210730101330_AddApplicantIdToVacancyCandidates.cs
  backend/src/Infrastructure/Migrations/20210804155854_ChangeCandidateToStageRelationToM2M.cs
Labels: bug

#39 delete extra class human
  backend/src/Domain/Entities/Applicant.cs
  backend/src/Domain/Entities/Human.cs
Labels: bug

#35 fix change page problem
  frontend/ATS/src/app/shared/directives/style-paginator.directive.ts
Labels: enhancement

#26 Implementing ICurrentUserContext
  backend/src/Application/Interfaces/ICurrentUserContext.cs
  backend/src/Infrastructure/Infrastructure.csproj
  backend/src/Infrastructure/Services/CurrentUserContext.cs
  backend/src/WebAPI/Controllers/AuthController.cs
  backend/src/WebAPI/Startup.cs
Labels: enhancement, backend api changes

#30 Feature serhiiyanchuk front end authorization
  backend/src/Application/Auth/Exceptions/ExpiredRefreshTokenException.cs
  backend/src/Application/Auth/Exceptions/InvalidTokenException.cs
  backend/src/WebAPI/Controllers/UsersController.cs
  backend/src/WebAPI/Middleware/ErrorHandlerMiddleware.cs
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/users/guards/auth.guard.ts
  frontend/ATS/src/app/users/helpers/error.interceptor.ts
  frontend/ATS/src/app/users/helpers/jwt.interceptor.ts
  frontend/ATS/src/app/users/models/auth/auth-user.ts
  frontend/ATS/src/app/users/models/auth/token-error-type.ts
  frontend/ATS/src/app/users/models/auth/user-login-dto.ts
  frontend/ATS/src/app/users/models/auth/user-register-dto.ts
  frontend/ATS/src/app/users/models/role.ts
  frontend/ATS/src/app/users/models/token/access-token.ts
  frontend/ATS/src/app/users/models/token/refresh-access-token-dto.ts
  frontend/ATS/src/app/users/models/user.ts
  frontend/ATS/src/app/users/services/auth.service.spec.ts
  frontend/ATS/src/app/users/services/auth.service.ts
Labels: enhancement

#36 Feature: file input
  frontend/ATS/src/app/shared/components/file-input/file-input.component.html
  frontend/ATS/src/app/shared/components/file-input/file-input.component.scss
  frontend/ATS/src/app/shared/components/file-input/file-input.component.ts
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.html
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.scss
  frontend/ATS/src/app/shared/components/topic/topic.component.html
  frontend/ATS/src/app/shared/components/topic/topic.component.scss
  frontend/ATS/src/app/shared/components/topic/topic.component.ts
  frontend/ATS/src/app/shared/shared.module.ts
Labels: enhancement

#51 Added applicants crud implementation
  .env.example/ats_api.env
  .gitignore
  backend/src/Application/Applicants/ApplicantProfile.cs
  backend/src/Application/Applicants/Commands/CreateComposedApplicantCommand.cs
  backend/src/Application/Applicants/Commands/UpdateComposedApplicantCommand.cs
  backend/src/Application/Applicants/Dtos/ApplicantDto.cs
  backend/src/Application/Applicants/Dtos/ApplicantVacancyInfoDto.cs
  backend/src/Application/Applicants/Dtos/CreateApplicantDto.cs
  backend/src/Application/Applicants/Dtos/UpdateApplicantDto.cs
  backend/src/Application/Applicants/Handlers/CreateApplicantCommandHandler.cs
  backend/src/Application/Applicants/Handlers/DeleteApplicantCommandHandler.cs
  backend/src/Application/Applicants/Handlers/GetApplicantByIdQuery.cs
  backend/src/Application/Applicants/Handlers/UpdateApplicantCommandHandler.cs
  backend/src/Application/Applicants/Profiles/ApplicantProfile.cs
  backend/src/Application/Applicants/Queries/GetComposedApplicantListQuery.cs
  backend/src/Application/Applicants/Queries/GetComposedApplicantQuery.cs
  backend/src/Application/ApplicationDependencyInjection.cs
  backend/src/Application/ElasticEntities/ElasticEntitiesProfile.cs
  backend/src/Application/ElasticEntities/Quaries/GetApplicantToTagsByIdQueryHandler/SearchApplicantToTagsQuery.cs
  backend/src/Domain/Entities/ApplicantVacancyInfo.cs
  backend/src/Domain/Interfaces/Read/IApplicantsReadRepository.cs
  backend/src/Infrastructure/Infrastructure.csproj
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Abstractions/ElasticWriteRepository.cs
  backend/src/Infrastructure/Repositories/Read/ApplicantsReadRepository.cs
  backend/src/Infrastructure/Repositories/Write/ApplicantsWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/common/common.scss
  frontend/ATS/src/app/applicants/common/scroll.scss
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.scss
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.spec.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.scss
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.spec.ts
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.ts
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.scss
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.spec.ts
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.ts
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/app/shared/models/applicant/applicant-vacancy-info.ts
  frontend/ATS/src/app/shared/models/applicant/applicant.ts
  frontend/ATS/src/app/shared/models/applicant/create-applicant.ts
  frontend/ATS/src/app/shared/models/applicant/update-applicant.ts
  frontend/ATS/src/app/shared/models/elastic-entity/elastic-entity.ts
  frontend/ATS/src/app/shared/models/elastic-entity/elastic-type.ts
  frontend/ATS/src/app/shared/models/tags/tag.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
  frontend/ATS/src/app/shared/shared.module.ts
Labels: enhancement

#44 Implement CRUD for Projects
  backend/src/Application/Projects/CommandQuery/Delete/DeleteProjectCommand.cs
  backend/src/Application/Projects/CommandQuery/Update/UpdateProjectCommand.cs
  backend/src/Application/Projects/CommandQuery/Update/UpdateProjectCommandValidator.cs
  backend/src/Application/Projects/Commands/Create/CreateProjectCommand.cs
  backend/src/Application/Projects/Commands/Create/CreateProjectCommandValidator.cs
  backend/src/Application/Projects/Dtos/ProjectDto.cs
  backend/src/Application/Projects/Dtos/ProjectGetDto.cs
  backend/src/Application/Projects/ProjectProfile.cs
  backend/src/Application/Projects/Queries/GetProjectByIdQuery.cs
  backend/src/Application/Projects/Queries/GetProjectListQuery.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Read/ProjectReadRepository.cs
  backend/src/WebAPI/Controllers/ProjectsController.cs
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.html
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.scss
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.ts
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.html
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.scss
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/projects/models/project-info.ts
  frontend/ATS/src/app/projects/project-routing.module.ts
  frontend/ATS/src/app/projects/projects.module.ts
  frontend/ATS/src/app/projects/services/projects.service.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/directives/style-paginator.directive.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/common.scss
Labels: enhancement, UIchange, backend api changes

#52 add auth header cors
  backend/src/WebAPI/Extensions/CorsExtension.cs
Labels: bug

#54 Added swagger authorisation with token
  backend/src/WebAPI/Middleware/Filters/AddAuthHeaderOperationFilter.cs
  backend/src/WebAPI/Startup.cs
Labels: enhancement, backend api changes

#55 Feature mykola levadnyi CRUD projects edit
  backend/src/Application/Projects/Dtos/ProjectGetDto.cs
  backend/src/Application/Vacancies/Dtos/VacancyTableDto.cs
  backend/src/Application/Vacancies/VacancyProfile.cs
  frontend/ATS/src/app/projects/project-routing.module.ts
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/menu/menu.component.html
Labels: enhancement, UIchange, backend api changes

#58 Fix succecfull registration and confirm email pages
  frontend/ATS/src/app/users/components/confirm-email/confirm-email.component.html
  frontend/ATS/src/app/users/components/confirm-email/confirm-email.component.scss
  frontend/ATS/src/app/users/components/confirm-email/confirm-email.component.ts
  frontend/ATS/src/app/users/components/successful-registration/successful-registration.component.html
  frontend/ATS/src/app/users/components/successful-registration/successful-registration.component.scss
  frontend/ATS/src/app/users/components/successful-registration/successful-registration.component.ts
Labels: bug

#60 Added logged in user guard
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/users/guards/logged-in-user.guard.ts
  frontend/ATS/src/app/users/user-routing.module.ts
  frontend/ATS/src/app/users/users.module.ts
Labels: enhancement

#59 Feature: logout
  backend/src/WebAPI/Extensions/CorsExtension.cs
  frontend/ATS/package-lock.json
  frontend/ATS/src/app/shared/components/header/header.component.html
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/app/shared/components/header/header.component.ts
Labels: enhancement

#71 Fixed logout
  frontend/ATS/src/app/shared/components/header/header.component.ts
Labels: enhancement

#74 API for loading csv with list of applicants
  backend/src/Application/Applicants/Commands/CreateApplicantsFromCsvCommand.cs
  backend/src/Application/Applicants/Dtos/ApplicantCsvDto.cs
  backend/src/Application/Applicants/Profiles/ApplicantProfile.cs
  backend/src/Application/Application.csproj
  backend/src/Domain/Interfaces/Write/IApplicantsFromCsvWriteRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Write/ApplicantsFromCsvWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
Labels: enhancement, backend api changes

#79 fix incorrect status codes token refresh & revoke
  backend/src/Infrastructure/Repositories/Read/RTokenReadRepository.cs
Labels: bug

#76 Feature nil application pool
  backend/src/Application/Applicants/Handlers/GetApplicantByIdQuery.cs
  backend/src/Application/Common/Queries/GetEntitiesFullListQuery.cs
  backend/src/Application/Common/Queries/GetEntityByIdQuery.cs
  backend/src/Application/Pools/Commands/Create/CreatePoolCommand.cs
  backend/src/Application/Pools/Commands/Create/CreatePoolCommandValidatior.cs
  backend/src/Application/Pools/Commands/Update/UpdatePoolCommand.cs
  backend/src/Application/Pools/Dtos/CreatePoolDto.cs
  backend/src/Application/Pools/Dtos/PoolApplicantDto.cs
  backend/src/Application/Pools/Dtos/PoolDto.cs
  backend/src/Application/Pools/Dtos/UpdatePoolDto.cs
  backend/src/Application/Pools/PoolProfile.cs
  backend/src/Application/Pools/Queries/GetPoolByIdFullQuery.cs
  backend/src/Application/Pools/Queries/GetPoolByIdQuery.cs
  backend/src/Application/Pools/Queries/GetPoolWithApplicantsByIdQuery.cs
  backend/src/Application/Pools/Queries/GetPoolsWithApplicantsQuery.cs
  backend/src/Application/Users/Queries/GetUserByIdQuery.cs
  backend/src/Domain/Entities/Pool.cs
  backend/src/Domain/Interfaces/Read/IApplicantReadRepository.cs
  backend/src/Domain/Interfaces/Read/IPoolReadRepository.cs
  backend/src/Domain/Interfaces/Write/IPoolToApplicantWriteRepository.cs
  backend/src/Infrastructure/EF/ApplicationDbContext.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Migrations/20210817193609_ModifyApplicationsPoolEntity.Designer.cs
  backend/src/Infrastructure/Migrations/20210817193609_ModifyApplicationsPoolEntity.cs
  backend/src/Infrastructure/Migrations/ApplicationDbContextModelSnapshot.cs
  backend/src/Infrastructure/Repositories/Abstractions/WriteRepository.cs
  backend/src/Infrastructure/Repositories/Read/ApplicantReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/PoolReadRepository.cs
  backend/src/Infrastructure/Repositories/Write/ApplicantsToPoolWriteRepository.cs
  backend/src/WebAPI/Controllers/PoolsController.cs
  backend/src/WebAPI/Startup.cs
  backend/src/WebAPI/WebAPI.csproj
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/app/components/app/app.component.scss
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/menu/menu.component.html
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.html
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.ts
  frontend/ATS/src/app/shared/models/applicants-pool/applicants-pool.ts
  frontend/ATS/src/app/shared/models/applicants-pool/create-pool.ts
  frontend/ATS/src/app/shared/models/applicants-pool/update-pool.ts
  frontend/ATS/src/app/shared/models/applicants/applicant.ts
  frontend/ATS/src/app/shared/services/poolService.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.spec.ts
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/users/components/create-talentpool-modal/create-talentpool-modal.component.html
  frontend/ATS/src/app/users/components/create-talentpool-modal/create-talentpool-modal.component.scss
  frontend/ATS/src/app/users/components/create-talentpool-modal/create-talentpool-modal.component.spec.ts
  frontend/ATS/src/app/users/components/create-talentpool-modal/create-talentpool-modal.component.ts
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.html
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.scss
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.spec.ts
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.ts
  frontend/ATS/src/app/users/components/home/home.component.scss
  frontend/ATS/src/app/users/users.module.ts
  frontend/ATS/tsconfig.json
Labels: enhancement, backend api changes

#80 fix auto refresh tokens
  frontend/ATS/src/app/users/components/forgot-password-dialog/forgot-password-dialog.component.scss
  frontend/ATS/src/app/users/helpers/error.interceptor.ts
Labels: bug

#81 Bugfix bogdan applicants table
  backend/src/Application/Applicants/Commands/CreateComposedApplicantCommand.cs
  backend/src/Application/Applicants/Commands/UpdateComposedApplicantCommand.cs
  backend/src/Application/Applicants/Dtos/CreateApplicantDto.cs
  backend/src/Application/Applicants/Dtos/UpdateApplicantDto.cs
  backend/src/Application/Applicants/Queries/GetComposedApplicantListQuery.cs
  backend/src/Application/ElasticEntities/ElasticEntitiesProfile.cs
  backend/src/Application/Users/Commands/RegisterUserCommand.cs
  backend/src/Domain/Interfaces/Read/IApplicantsReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/ReadRepository.cs
  backend/src/Infrastructure/Repositories/Abstractions/WriteRepository.cs
  backend/src/Infrastructure/Repositories/Read/ApplicantsReadRepository.cs
  backend/src/Infrastructure/Repositories/Write/ApplicantsWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  backend/src/WebAPI/Controllers/RegisterController.cs
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/common/common.scss
  frontend/ATS/src/app/applicants/common/scroll.scss
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.html
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.scss
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.spec.ts
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.spec.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.scss
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.scss
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.ts
  frontend/ATS/src/app/applicants/components/tags-edit/tags-edit.component.html
  frontend/ATS/src/app/applicants/components/tags-edit/tags-edit.component.scss
  frontend/ATS/src/app/applicants/components/tags-edit/tags-edit.component.spec.ts
  frontend/ATS/src/app/applicants/components/tags-edit/tags-edit.component.ts
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.scss
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.ts
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/shared/models/applicant/create-applicant.ts
  frontend/ATS/src/app/shared/models/applicant/update-applicant.ts
  frontend/ATS/src/app/shared/models/applicant/viewable-applicant.ts
  frontend/ATS/src/app/shared/models/elastic-entity/elastic-entity.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
Labels: bug

#87 UI bugs fix
  backend/src/Infrastructure/Services/CurrentUserContext.cs
  backend/src/WebAPI/Controllers/ProjectsController.cs
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.html
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.scss
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.html
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/shared/components/search-form/search-form.component.scss
  frontend/ATS/src/app/users/components/forgot-password-dialog/forgot-password-dialog.component.html
  frontend/ATS/src/app/users/components/forgot-password-dialog/forgot-password-dialog.component.scss
  frontend/ATS/src/app/users/components/login-box/login-box.component.html
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.scss
  frontend/ATS/src/app/users/components/registration-box/registration-box.component.html
  frontend/ATS/src/app/users/components/reset-password-box/reset-password-box.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
  frontend/ATS/src/common.scss
Labels: bug, UIchange, backend api changes

#88 Add max-width: fit-content
  frontend/ATS/src/common.scss
Labels: bug, UIchange

#92 Fixed logout menu style
  backend/src/Infrastructure/EF/Seeds/UserSeeds.cs
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/header/header.component.html
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/app/shared/components/header/header.component.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.scss
  frontend/ATS/src/app/vacancies/vacancies-routing.module.ts
Labels: enhancement

#93 add candidate modal window
  backend/src/Application/Applicants/Dtos/GetApplicantDto.cs
  backend/src/Application/Applicants/Dtos/GetShortApplicantDto.cs
  backend/src/Application/Applicants/Dtos/MarkedApplicantDto.cs
  backend/src/Application/Applicants/Profiles/ApplicantProfile.cs
  backend/src/Application/Applicants/Queries/GetApplicantByIdByCompanyQuery.cs
  backend/src/Application/Applicants/Queries/GetApplicantsWithAppliedMark.cs
  backend/src/Application/Vacancies/Dtos/ShortVacancyWithDepartmentDto.cs
  backend/src/Application/Vacancies/Queries/GetNotAppliedVacanciesByApplicantIdQuery.cs
  backend/src/Application/Vacancies/Queries/GetVacancyByIdQuery.cs
  backend/src/Application/Vacancies/VacancyProfile.cs
  backend/src/Application/VacancyCandidates/Commands/CreateVacancyCandidateRangeCommand.cs
  backend/src/Domain/Interfaces/Read/IApplicantsReadRepository.cs
  backend/src/Domain/Interfaces/Read/IStageReadRepository.cs
  backend/src/Domain/Interfaces/Read/IVacancyReadRepository.cs
  backend/src/Domain/Interfaces/Write/IVacancyCandidateWriteRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Read/ApplicantsReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/StageReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/VacancyReadRepository.cs
  backend/src/Infrastructure/Repositories/Write/VacancyCandidateWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  backend/src/WebAPI/Controllers/VacanciesController.cs
  backend/src/WebAPI/Controllers/VacancyCandidatesController.cs
  frontend/ATS/src/app/applicants/models/MarkedApplicant.ts
  frontend/ATS/src/app/applicants/models/Vacancy.ts
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.html
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.scss
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.ts
  frontend/ATS/src/app/shared/models/applicant/get-applicant.ts
  frontend/ATS/src/app/shared/models/applicant/get-short-applicant.ts
  frontend/ATS/src/app/shared/models/applicant/marked-applicant.ts
  frontend/ATS/src/app/shared/models/vacancy/short-vacancy-with-department.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
  frontend/ATS/src/app/shared/services/vacancy-candidate.service.ts
  frontend/ATS/src/app/shared/services/vacancy-data.service.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
  frontend/ATS/src/app/vacancies/vacancies-routing.module.ts
Labels: enhancement, UIchange, backend api changes

#90 Added confirm message while deleting an applicant and changed some styles
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/common/common.scss
  frontend/ATS/src/app/applicants/common/scroll.scss
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.html
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.scss
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicant-delete-confirm/applicant-delete-confirm.component.html
  frontend/ATS/src/app/applicants/components/applicant-delete-confirm/applicant-delete-confirm.component.scss
  frontend/ATS/src/app/applicants/components/applicant-delete-confirm/applicant-delete-confirm.component.spec.ts
  frontend/ATS/src/app/applicants/components/applicant-delete-confirm/applicant-delete-confirm.component.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.scss
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.scss
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
Labels: bug, enhancement, UIchange

#95 add delete projects button
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
Labels: enhancement, UIchange

#97 Added app-button component instead of simple button in applicants header
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
Labels: UIchange

#100 Add applicant to vacancy button and fix some projects bugs
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.html
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.scss
  frontend/ATS/src/app/projects/components/project-delete-confirm/project-delete-confirm.component.html
  frontend/ATS/src/app/projects/components/project-delete-confirm/project-delete-confirm.component.scss
  frontend/ATS/src/app/projects/components/project-delete-confirm/project-delete-confirm.component.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/projects/projects.module.ts
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.html
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.ts
  frontend/ATS/src/app/shared/services/vacancy-candidate.service.ts
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: bug, enhancement, UIchange

#103 fix refresh tokens when db's dropped
  backend/src/WebAPI/Extensions/JwtExtension.cs
  frontend/ATS/src/app/shared/components/header/header.component.ts
  frontend/ATS/src/app/users/helpers/error.interceptor.ts
  frontend/ATS/src/app/users/services/auth.service.ts
Labels: bug

#105 Feature nil application pool details
  backend/src/Application/Pools/Commands/Create/CreatePoolCommand.cs
  backend/src/Application/Pools/Dtos/PoolApplicantDto.cs
  backend/src/Application/Pools/Dtos/PoolDto.cs
  backend/src/Application/Pools/PoolProfile.cs
  backend/src/Application/Pools/Queries/GetPoolWithApplicantsByIdQuery.cs
  backend/src/Application/Pools/Queries/GetPoolsWithApplicantsQuery.cs
  backend/src/Domain/Entities/Pool.cs
  backend/src/Infrastructure/Repositories/Read/PoolReadRepository.cs
  backend/src/WebAPI/Controllers/PoolsController.cs
  frontend/ATS/src/app/app/app.module.ts
  frontend/ATS/src/app/pools/components/application-pool-details/application-pool-details.component.html
  frontend/ATS/src/app/pools/components/application-pool-details/application-pool-details.component.scss
  frontend/ATS/src/app/pools/components/application-pool-details/application-pool-details.component.ts
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/pools/components/create-talentpool-modal/create-talentpool-modal.component.html
  frontend/ATS/src/app/pools/components/create-talentpool-modal/create-talentpool-modal.component.scss
  frontend/ATS/src/app/pools/components/create-talentpool-modal/create-talentpool-modal.component.ts
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.html
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.scss
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.ts
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.html
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.scss
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.ts
  frontend/ATS/src/app/pools/pools-routing.module.ts
  frontend/ATS/src/app/pools/pools.module.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/models/applicant/applicant-select.ts
  frontend/ATS/src/app/shared/models/applicant/applicant.ts
  frontend/ATS/src/app/shared/models/applicants-pool/applicants-pool.ts
  frontend/ATS/src/app/shared/models/applicants/applicant.ts
  frontend/ATS/src/app/shared/models/vacancy-candidates/short-with-applicant.ts
  frontend/ATS/src/app/shared/services/poolService.ts
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/users/components/application-pool/application-pool.component.spec.ts
  frontend/ATS/src/app/users/components/create-talentpool-modal/create-talentpool-modal.component.spec.ts
  frontend/ATS/src/app/users/components/edit-app-pool-modal/edit-app-pool-modal.component.spec.ts
  frontend/ATS/src/app/users/users.module.ts
Labels: enhancement, backend api changes

#111 Fixed bug with history form all vacancies
  backend/src/Application/VacancyCandidates/Queries/GetFullByIdQuery.cs
  backend/src/Domain/Interfaces/Read/IVacancyCandidateReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/VacancyCandidateReadRepository.cs
  backend/src/WebAPI/Controllers/VacancyCandidatesController.cs
  frontend/ATS/src/app/shared/services/vacancy-candidate.service.ts
  frontend/ATS/src/app/vacancies/components/one-candidate-modal/one-candidate-modal.component.html
  frontend/ATS/src/app/vacancies/components/one-candidate-modal/one-candidate-modal.component.ts
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement

#113 Fixed candidate review modal
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.ts
  frontend/ATS/src/app/shared/models/applicants-pool/applicants-pool.ts
Labels: enhancement

#110 fix error when tags dto empty
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.html
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.ts
Labels: bug

#114 Fix VacancyId
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement

#109 Feature serhiiyanchuk improvement user table
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.scss
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/users/models/user-table-data.ts
  frontend/ATS/src/app/users/services/user-data.service.ts
Labels: enhancement, UIchange

#124 Fixed mail template
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Mongo/Seeding/MailTemplatesSeeds.cs
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
Labels: enhancement

#126 Fixed vacancy stages-candidate board styles
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.scss
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
  frontend/ATS/src/common.scss
Labels: enhancement

#127 Bugfix nil css pooldetails createpool
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.html
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.ts
Labels: bug, enhancement

#130 Fixed seeding
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
Labels: enhancement

#131 Fix projectReadRepository + Vacancy add/edit styles
  backend/src/Application/Projects/Commands/GetProjectsByCurrentHRCompanyCommand.cs
  backend/src/Domain/Interfaces/Read/IProjectReadRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Read/ProjectReadRepository.cs
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
Labels: bug

#129 Added front load from csv
  backend/src/Application/Applicants/Commands/CreateApplicantsFromCsvCommand.cs
  backend/src/Application/Applicants/Dtos/ApplicantCsvDto.cs
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.html
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.scss
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/shared/enums/file-type.enum.ts
  frontend/ATS/src/app/shared/models/file/file.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
Labels: enhancement, UIchange

#132 Fixed bug with null exception while updating a recently created appli…
  backend/src/Application/Applicants/Commands/CreateApplicant/CreateApplicantCommand.cs
Labels: bug

#133 Fix edit stage
  frontend/ATS/src/app/users/components/confirm-email/confirm-email.component.html
  frontend/ATS/src/app/users/components/successful-registration/successful-registration.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.html
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.scss
Labels: bug

#136 Delete interpolation and UI fix bugs
  backend/src/Infrastructure/Repositories/Read/ApplicantReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/ProjectReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/StageReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/UserReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/VacancyReadRepository.cs
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.html
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.scss
Labels: bug, refactor

#140 Fix bugs in vacancy edit and table
  backend/src/Application/Stages/Commands/Update/EditVacancyStageCommand.cs
  backend/src/Domain/Enums/StageType.cs
  backend/src/Infrastructure/EF/Seeds/StageSeeds.cs
  frontend/ATS/src/app/shared/models/stages/type.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.html
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.scss
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
Labels: bug

#141 Fix to-board button
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: UIchange

#168 Hotfix: candidate moving
  backend/src/Application/VacancyCandidates/Commands/ChangeCandidateStageCommand.cs
  backend/src/Infrastructure/Repositories/Write/CandidateToStageWriteRepository.cs
  backend/src/Infrastructure/Repositories/Write/VacancyCandidateWriteRepository.cs
Labels: enhancement

#164 Feature serhiiyanchuk info home page
  backend/src/Application/Home/Dtos/HotVacancySummaryDto.cs
  backend/src/Application/Home/Dtos/ShortVacancyDto.cs
  backend/src/Application/Home/Dtos/WidgetsDataDto.cs
  backend/src/Application/Home/HomeDataProfile.cs
  backend/src/Application/Home/Queries/GetHotVacancySummaryQuery.cs
  backend/src/Application/Home/Queries/GetWidgetsInfoQuery.cs
  backend/src/Domain/Entities/HomeData/HotVacancySummary.cs
  backend/src/Domain/Entities/HomeData/WidgetsData.cs
  backend/src/Domain/Interfaces/Read/IHomeDataReadRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Read/HomeDataReadRepository.cs
  backend/src/WebAPI/Controllers/HomeController.cs
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/models/vacancy/vacancy-model.ts
  frontend/ATS/src/app/shared/models/vacancy/vacancy-widget.ts
  frontend/ATS/src/app/users/components/home-page/home-widget/home-widget.component.html
  frontend/ATS/src/app/users/components/home-page/home-widget/home-widget.component.scss
  frontend/ATS/src/app/users/components/home-page/home-widget/home-widget.component.spec.ts
  frontend/ATS/src/app/users/components/home-page/home-widget/home-widget.component.ts
  frontend/ATS/src/app/users/components/home-page/home/home.component.html
  frontend/ATS/src/app/users/components/home-page/home/home.component.scss
  frontend/ATS/src/app/users/components/home-page/home/home.component.spec.ts
  frontend/ATS/src/app/users/components/home-page/home/home.component.ts
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.html
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.scss
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.spec.ts
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.ts
  frontend/ATS/src/app/users/components/home/home.component.html
  frontend/ATS/src/app/users/components/home/home.component.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.scss
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/users/models/home/home-widget-data.ts
  frontend/ATS/src/app/users/models/home/hot-vacancy-summary.ts
  frontend/ATS/src/app/users/models/home/short-vacancy.ts
  frontend/ATS/src/app/users/models/home/widgets-data.ts
  frontend/ATS/src/app/users/services/home-data.service.ts
  frontend/ATS/src/app/users/user-routing.module.ts
  frontend/ATS/src/app/users/users.module.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
  frontend/ATS/src/app/vacancies/components/vacancy-card/vacancy-card.component.html
  frontend/ATS/src/app/vacancies/components/vacancy-card/vacancy-card.component.ts
  frontend/ATS/src/app/vacancies/components/vacancy-widget/vacancy-widget.component.html
  frontend/ATS/src/app/vacancies/components/vacancy-widget/vacancy-widget.component.ts
Labels: enhancement, UIchange, backend api changes

#159 Upload applicants from csv UI
  backend/src/Application/Applicants/Commands/CreateApplicant/CreateRangeOfApplicantsCommand.cs
  backend/src/Application/Applicants/Commands/CreateApplicantsFromCsvCommand.cs
  backend/src/Application/Applicants/Dtos/ApplicantCsvDto.cs
  backend/src/Application/Applicants/Dtos/GetApplicantCsvDto.cs
  backend/src/Application/Applicants/Profiles/ApplicantProfile.cs
  backend/src/Application/Applicants/Queries/CetApplicantsFromCsvCommand.cs
  backend/src/Domain/Interfaces/Read/IApplicantReadRepository.cs
  backend/src/Domain/Interfaces/Write/IApplicantsFromCsvWriteRepository.cs
  backend/src/Infrastructure/Repositories/Read/ApplicantReadRepository.cs
  backend/src/Infrastructure/Repositories/Write/ApplicantsFromCsvWriteRepository.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/components/applicant-csv-list/applicant-csv-list.component.html
  frontend/ATS/src/app/applicants/components/applicant-csv-list/applicant-csv-list.component.scss
  frontend/ATS/src/app/applicants/components/applicant-csv-list/applicant-csv-list.component.ts
  frontend/ATS/src/app/applicants/components/applicant-update-csv/applicant-update-csv.component.html
  frontend/ATS/src/app/applicants/components/applicant-update-csv/applicant-update-csv.component.scss
  frontend/ATS/src/app/applicants/components/applicant-update-csv/applicant-update-csv.component.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.html
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.scss
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.ts
  frontend/ATS/src/app/applicants/models/CsvApplicant.ts
  frontend/ATS/src/app/applicants/models/MarkedApplicant.ts
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.ts
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/models/applicants/create-applicant.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
  frontend/ATS/src/app/shared/shared.module.ts
Labels: enhancement, UIchange, backend api changes

#171 hotfix upload csv
  frontend/ATS/src/app/applicants/components/self-applying/self-applying.component.ts
  frontend/ATS/src/app/shared/models/applicants/create-applicant.ts
  frontend/ATS/src/app/shared/shared.module.ts
Labels: bug

#172 Fixed styles in stages-candidates board and all connected components
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/rate-candidate-modal/rate-candidate-modal.component.html
  frontend/ATS/src/app/vacancies/components/rate-candidate-modal/rate-candidate-modal.component.scss
  frontend/ATS/src/app/vacancies/components/rate-candidate-modal/rate-candidate-modal.component.ts
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.html
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement

#173 fix home page styles
  frontend/ATS/src/app/shared/components/main-content/main-content.component.scss
  frontend/ATS/src/app/shared/components/search-form/search-form.component.scss
  frontend/ATS/src/app/users/components/home-page/home-widget/home-widget.component.scss
  frontend/ATS/src/app/users/components/home-page/home/home.component.html
  frontend/ATS/src/app/users/components/home-page/home/home.component.scss
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.html
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.scss
Labels: UIchange

#176 Fix serhiiyanchuk selfapplied home data
  backend/src/Application/Home/Queries/GetHotVacancySummaryQuery.cs
  backend/src/Domain/Entities/HomeData/HotVacancySummary.cs
  backend/src/Infrastructure/Repositories/Read/HomeDataReadRepository.cs
  frontend/ATS/src/app/users/components/home-page/home/home.component.scss
Labels: UIchange

#178 Styles fix
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.html
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.scss
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
Labels: bug

#179 fix auth pages styles
  frontend/ATS/src/app/users/components/forgot-password-dialog/forgot-password-dialog.component.scss
  frontend/ATS/src/app/users/components/login-regist-common/login-regist-common.component.scss
Labels: bug, UIchange

#180 Added recent activity for every applicant
  backend/src/Application/Applicants/Commands/CreateApplicant/CreateSelfAppliedApplicantCommand.cs
  backend/src/Application/CandidateToStages/CandidateToStageProfile.cs
  backend/src/Application/CandidateToStages/Dtos/CandidateToStageApplicantRecentActivityDto.cs
  backend/src/Application/CandidateToStages/Dtos/VacancyWithRecentActivityDto.cs
  backend/src/Application/CandidateToStages/Queries/GetRecentActivityForApplicantQuery.cs
  backend/src/Domain/Interfaces/Read/IApplicantReadRepository.cs
  backend/src/Domain/Interfaces/Read/ICandidateToStageReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/CandidateToStageReadRepository.cs
  backend/src/Infrastructure/Repositories/Read/VacancyCandidateReadRepository.cs
  backend/src/WebAPI/Controllers/RecentActivityController.cs
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.html
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicant-history/applicant-history.component.html
  frontend/ATS/src/app/applicants/components/applicant-history/applicant-history.component.scss
  frontend/ATS/src/app/applicants/components/applicant-history/applicant-history.component.ts
  frontend/ATS/src/app/shared/models/candidate-to-stages/applicant-recent-activity.ts
  frontend/ATS/src/app/shared/models/candidate-to-stages/vacancy-with-recent-activity.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
Labels: enhancement

#182 Bugfix mykola levadnyi applicant page styles
  backend/src/Application/Common/Mail/MailBodyFactory.cs
  backend/src/WebAPI/Controllers/VacanciesController.cs
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/shared/services/followedService.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: bug, enhancement, UIchange

#184 Complex style fix 1
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.ts
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
  frontend/ATS/src/app/vacancies/components/candidate-card/candidate-card.component.html
  frontend/ATS/src/app/vacancies/components/candidate-card/candidate-card.component.ts
  frontend/ATS/src/app/vacancies/components/candidate-column/candidate-column.component.scss
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.html
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.scss
  frontend/LinkedInScoutExtension/chrome/script.js
Labels: enhancement

#183 add start sort by creation date column
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/projects/models/project-info.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/users/models/user-table-data.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
Labels: UIchange

#185 Try to fix card moving
  backend/src/Infrastructure/Repositories/Write/CandidateToStageWriteRepository.cs
Labels: enhancement

#186 Showing one candidate modal on link click (home page)
  backend/src/Application/CandidateToStages/CandidateToStageProfile.cs
  backend/src/Application/CandidateToStages/Dtos/CandidateToStageRecentActivityDto.cs
  backend/src/Infrastructure/Repositories/Read/CandidateToStageReadRepository.cs
  frontend/ATS/src/app/shared/models/candidate-to-stages/recent-activity.ts
  frontend/ATS/src/app/users/components/recent-activity/recent-activity.component.html
  frontend/ATS/src/app/users/components/recent-activity/recent-activity.component.ts
  frontend/ATS/src/common.scss
Labels: enhancement
