Repository BinaryStudioAcademy/bsa-2021-ats, pull requests merged in 2021-09, with the labels that each got.

#192 Fixed candidate moving
  backend/src/Application/Pools/Commands/Create/CreatePoolCommand.cs
  backend/src/Application/Projects/Commands/Create/CreateProjectCommand.cs
  backend/src/Application/Vacancies/Commands/Edit/EditVacancyCommand.cs
  backend/src/Application/VacancyCandidates/Commands/ChangeCandidateStageCommand.cs
  backend/src/Application/VacancyCandidates/Commands/CreateVacancyCandidateNoAuthCommand.cs
  backend/src/Application/VacancyCandidates/Commands/CreateVacancyCandidateRangeCommand.cs
  backend/src/Application/VacancyCandidates/EventHandlers/CandidateStageChangedEventHandler.cs
  backend/src/Domain/Events/CandidateStageChangedEvent.cs
  backend/src/Domain/Interfaces/Write/ICandidateToStageWriteRepository.cs
  backend/src/Infrastructure/AWS/S3/AwsS3ReadRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Write/CandidateToStageWriteRepository.cs
  backend/src/WebAPI/Controllers/VacancyCandidatesController.cs
  frontend/ATS/src/app/shared/services/vacancy-candidate.service.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement

#195 applicant from variant fix
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.ts
Labels: bug

#197 csv uploading upgrade
  backend/src/Application/ApplicantCsvs/ApplicantCsvProfile.cs
  backend/src/Application/ApplicantCsvs/Commands/CreateCsvFileCommand.cs
  backend/src/Application/ApplicantCsvs/Commands/UpdateCsvFileCommand.cs
  backend/src/Application/ApplicantCsvs/Dtos/CsvFileDto.cs
  backend/src/Application/ApplicantCsvs/Queries/GetCsvFilesEnumerableQuery.cs
  backend/src/Application/Applicants/Commands/CreateApplicant/CreateCsvApplicantCommand.cs
  backend/src/Application/Applicants/Commands/CreateApplicant/CreateRangeOfApplicantsCommand.cs
  backend/src/Application/Applicants/Dtos/ApplicantCsvGetDto.cs
  backend/src/Application/Applicants/Profiles/ApplicantProfile.cs
  backend/src/Application/Applicants/Queries/GetApplicantsFromCsvCommand.cs
  backend/src/Domain/Entities/CsvFile.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/WebAPI/Controllers/ApplicantCsvController.cs
  backend/src/WebAPI/Controllers/ApplicantsController.cs
  frontend/ATS/src/app/applicants/applicants.module.ts
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-file-tables/applicant-csv-file-tables.component.html
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-file-tables/applicant-csv-file-tables.component.scss
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-file-tables/applicant-csv-file-tables.component.ts
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-files-list/applicant-csv-files-list.component.html
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-files-list/applicant-csv-files-list.component.scss
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-files-list/applicant-csv-files-list.component.ts
  frontend/ATS/src/app/applicants/components/CsvComponents/applicants-upload-csv/applicants-upload-csv.component.html
  frontend/ATS/src/app/applicants/components/CsvComponents/applicants-upload-csv/applicants-upload-csv.component.scss
  frontend/ATS/src/app/applicants/components/CsvComponents/applicants-upload-csv/applicants-upload-csv.component.ts
  frontend/ATS/src/app/applicants/components/CsvComponents/one-csv-file/one-csv-file.component.html
  frontend/ATS/src/app/applicants/components/CsvComponents/one-csv-file/one-csv-file.component.scss
  frontend/ATS/src/app/applicants/components/CsvComponents/one-csv-file/one-csv-file.component.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.scss
  frontend/ATS/src/app/applicants/components/applicants-upload-csv/applicants-upload-csv.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/applicants/models/CsvApplicant.ts
  frontend/ATS/src/app/applicants/models/CsvFile.ts
  frontend/ATS/src/app/applicants/services/applicant-csv.service.ts
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/services/applicants.service.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement, UIchange, backend api changes

#201 Fix html editor css
  frontend/ATS/angular.json
  frontend/ATS/package-lock.json
  frontend/ATS/package.json
  frontend/ATS/tsconfig.app.json
Labels: bug

#200 Apply pool applicants to vacancy
  backend/src/Application/Vacancies/Queries/GetShortVacanciesWithDepartmentQuery.cs
  backend/src/WebAPI/Controllers/VacanciesController.cs
  frontend/ATS/src/app/applicants/components/CsvComponents/applicant-csv-files-list/applicant-csv-files-list.component.scss
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.html
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.scss
  frontend/ATS/src/app/applicants/components/self-applying/self-applying.component.html
  frontend/ATS/src/app/applicants/components/self-applying/self-applying.component.ts
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.scss
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.ts
  frontend/ATS/src/app/shared/services/vacancy-data.service.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
  frontend/ATS/src/common.scss
Labels: enhancement, UIchange, backend api changes

#204 Fixed filter bug
  frontend/ATS/src/app/shared/components/table-filter/table-filter.component.ts
Labels: enhancement

#203 Redesign one candidate
  frontend/ATS/package-lock.json
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.html
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.scss
Labels: enhancement

#202 Add command for replacing placeholders in template
  backend/src/Application/MailTemplates/Commands/CreateMailTemplateCommand.cs
  backend/src/Application/MailTemplates/Dtos/MailTemplateSendDto.cs
  backend/src/Application/MailTemplates/MailTemplateProfile.cs
  backend/src/Application/MailTemplates/Queries/GetMailTemplateWithReplacedPlaceholdersQuery.cs
  backend/src/Application/MailTemplates/Queries/GetMailWithAttachmentFilesTemplateQuery.cs
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.scss
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.scss
  frontend/ATS/src/app/users/components/placeholders/placeholders.component.html
Labels: enhancement

#206 Added parsing email and phone from linkedin
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
  frontend/LinkedInScoutExtension/chrome/script.js
Labels: enhancement

#212 Removed analytics and and added project link on home page
  backend/src/Application/Home/Dtos/HotVacancySummaryDto.cs
  backend/src/Application/Home/Queries/GetHotVacancySummaryQuery.cs
  backend/src/Domain/Entities/HomeData/HotVacancySummary.cs
  backend/src/Infrastructure/Repositories/Read/HomeDataReadRepository.cs
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/routing/AppRoute.ts
  frontend/ATS/src/app/routing/routing.module.ts
  frontend/ATS/src/app/shared/components/menu/menu.component.html
  frontend/ATS/src/app/users/components/home-page/vacancy-card/vacancy-card.component.html
  frontend/ATS/src/app/users/models/home/hot-vacancy-summary.ts
Labels: enhancement

#213 Fix create/edit vacany form
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.ts
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.ts
  frontend/ATS/src/app/shared/services/mail-template.service.ts
  frontend/ATS/src/app/users/components/placeholders/placeholders.component.ts
  frontend/ATS/src/app/users/helpers/error.interceptor.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.ts
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.html
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.scss
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.ts
  frontend/ATS/src/app/vacancies/components/stages/stage/stage.component.html
  frontend/ATS/src/app/vacancies/components/stages/stage/stage.component.scss
Labels: bug

#214 Add mail template seeding
  backend/src/Infrastructure/Mongo/Seeding/MailTemplatesSeeds.cs
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.html
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.ts
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.html
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.ts
Labels: enhancement

#217 fix mongo seeding
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
Labels: bug

#211 Fix: filter and timeline
  backend/src/Application/Vacancies/Commands/Delete/DeleteVacancyCommand.cs
  backend/src/Application/VacancyCandidates/Commands/ChangeCandidateStageCommand.cs
  backend/src/Domain/Interfaces/Write/ICandidateToStageWriteRepository.cs
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Repositories/Write/CandidateToStageWriteRepository.cs
  backend/src/WebAPI/Controllers/VacancyCandidatesController.cs
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/shared/components/table-filter/table-filter.component.html
  frontend/ATS/src/app/shared/components/table-filter/table-filter.component.scss
  frontend/ATS/src/app/shared/components/table-filter/table-filter.component.ts
  frontend/ATS/src/app/shared/date-adapters/timezone.date-adapter.ts
  frontend/ATS/src/app/shared/shared.module.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.scss
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/vacancies/components/one-candidate/one-candidate.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: enhancement

#220 Fixed variants modal and applicants
  backend/src/Application/VacancyCandidates/Commands/ChangeCandidateStageCommand.cs
  backend/src/Application/VacancyCandidates/Commands/CreateVacancyCandidateRangeCommand.cs
  backend/src/Infrastructure/Repositories/Read/CandidateToStageReadRepository.cs
  backend/src/WebAPI/Controllers/VacancyCandidatesController.cs
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.scss
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.ts
  frontend/ATS/src/app/users/guards/auth.guard.ts
  frontend/LinkedInScoutExtension/chrome/script.js
Labels: enhancement

#222 Global consistency fixed
  backend/src/Application/Common/Mail/MailBodyFactory.cs
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/self-applying/self-applying.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.html
  frontend/ATS/src/app/mail-templates/components/mail-template-add/mail-template-add.component.scss
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.html
  frontend/ATS/src/app/mail-templates/components/mail-template-edit/mail-template-edit.component.scss
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.scss
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/pools/components/create-talentpool-modal/create-talentpool-modal.component.scss
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.html
  frontend/ATS/src/app/pools/components/edit-app-pool-modal/edit-app-pool-modal.component.scss
  frontend/ATS/src/app/pools/components/pool-details-modal/pool-details-modal.component.html
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.html
  frontend/ATS/src/app/projects/components/projects-add/projects-add.component.scss
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.html
  frontend/ATS/src/app/projects/components/projects-edit/projects-edit.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/shared/components/header/header.component.ts
  frontend/ATS/src/app/shared/components/modal-add-candidate/modal-add-candidate.component.scss
  frontend/ATS/src/app/task-management/components/main-page/main-page.component.html
  frontend/ATS/src/app/task-management/components/main-page/main-page.component.scss
  frontend/ATS/src/app/task-management/components/modal/all-in-one/all-in-one.component.scss
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
  frontend/ATS/src/common.scss
Labels: UIchange

#223 Task + Interview page fix
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.html
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.scss
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.scss
  frontend/ATS/src/app/task-management/components/main-page/main-page.component.scss
Labels: UIchange

#224 projects actions padding fix
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
Labels: UIchange

#226 Fixed filter
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.ts
  frontend/ATS/src/app/shared/components/table-filter/table-filter.component.ts
  frontend/ATS/src/app/shared/date-adapters/timezone.date-adapter.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: enhancement

#187 Feature bogdan vault
  .docker/docker-compose.develop-deployment.yml
  .docker/docker-compose.prod-deployment.yml
  .docker/docker-compose.services.yml
  .docker/docker-compose.yml
  .env.example/ats_api.env
  .env.example/ats_vault_client.env
  .env.example/ats_vault_server.env
  backend/src/Application/ApplicantCvs/Commands/FinishParsingCvFileToApplicantCommand.cs
  backend/src/Application/Interfaces/ISmtpFactory.cs
  backend/src/Application/Mail/SendMailCommand.cs
  backend/src/Application/Users/Commands/SendConfirmEmailMailCommand.cs
  backend/src/Domain/Interfaces/Read/IVaultReadRepository.cs
  backend/src/Infrastructure/Infrastructure.csproj
  backend/src/Infrastructure/InfrastructureDependencyInjection.cs
  backend/src/Infrastructure/Mail/GmailSmtpFactory.cs
  backend/src/Infrastructure/Repositories/Read/VaultReadRepository.cs
  backend/src/Infrastructure/Vault/Context/VaultContext.cs
  backend/src/Infrastructure/Vault/Extensions/VaultConfigurationExtension.cs
  backend/src/Infrastructure/Vault/Interfaces/IVaultConnectionFactory.cs
  backend/src/Infrastructure/Vault/Models/Secret.cs
  backend/src/Infrastructure/Vault/Models/VaultCredentialsWrapper.cs
  backend/src/Infrastructure/Vault/Models/VaultOptions.cs
  backend/src/Infrastructure/Vault/VaultConnectionFactory.cs
  backend/src/WebAPI/Properties/example.launchSettings.json
  backend/src/WebAPI/Startup.cs
  backend/src/WebAPI/appsettings.json
  database/Dockerfile
  database/entrypoint.sh
  database/import-data.sh
  database/secrets.csv
  database/setup.sql
  vault/Dockerfile
  vault/vault_setup.sh
Labels: enhancement

#227 Fix: applicants
  frontend/ATS/src/app/applicants/components/applicants-head/applicants-head.component.ts
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
  frontend/ATS/src/app/applicants/validators/applicant-validator.ts
  frontend/ATS/src/app/shared/date-adapters/timezone.date-adapter.ts
  frontend/ATS/src/app/users/guards/auth.guard.ts
Labels: enhancement

#231 Added asterisks
  frontend/ATS/src/app/applicants/components/create-applicant-from-variants/create-applicant-from-variants.component.html
  frontend/ATS/src/app/applicants/components/create-applicant/create-applicant.component.html
  frontend/ATS/src/app/applicants/components/update-applicant/update-applicant.component.html
Labels: enhancement

#236 change menu icons
  frontend/ATS/src/app/shared/components/menu/menu.component.html
Labels: UIchange

#237 Added view profile link
  frontend/ATS/src/app/vacancies/components/candidate-card/candidate-card.component.html
  frontend/ATS/src/app/vacancies/components/candidate-card/candidate-card.component.scss
  frontend/ATS/src/app/vacancies/components/candidate-card/candidate-card.component.ts
Labels: enhancement

#241 fix sql in VacancyReadRepository
  backend/src/Infrastructure/Repositories/Read/VacancyReadRepository.cs
Labels: bug

#243 Bugfix serhiiyanchuk sorting
  backend/src/Infrastructure/EF/Seeds/UserSeeds.cs
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.ts
  frontend/ATS/src/app/archive/components/project-archive/project-archive.component.html
  frontend/ATS/src/app/archive/components/project-archive/project-archive.component.scss
  frontend/ATS/src/app/archive/components/project-archive/project-archive.component.ts
  frontend/ATS/src/app/archive/components/vacancy-archive/vacancy-archive.component.scss
  frontend/ATS/src/app/archive/components/vacancy-archive/vacancy-archive.component.ts
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.html
  frontend/ATS/src/app/pools/components/application-pool/application-pool.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.html
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.scss
  frontend/ATS/src/app/projects/components/projects-list/projects-list.component.ts
  frontend/ATS/src/app/users/components/hr-lead/users-table/users-table.component.ts
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.html
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.scss
  frontend/ATS/src/app/vacancies/components/vacancies-table/vacancies-table.component.ts
Labels: bug, UIchange

#244 Feature mykola levadnyi add interview action
  backend/src/Application/Interviews/Commands/Update/UpdateInterviewCommand.cs
  backend/src/Application/Interviews/Dtos/CreateInterviewDto.cs
  backend/src/Application/Interviews/Dtos/InterviewDto.cs
  backend/src/Application/Interviews/Queries/GetInterviewsListQuery.cs
  backend/src/Application/VacancyCandidates/EventHandlers/CandidateStageChangedEventHandler.cs
  backend/src/Infrastructure/EF/Seeds/InterviewSeeds.cs
  frontend/ATS/src/app/interviews/components/create-interview/create-interview.component.ts
  frontend/ATS/src/app/interviews/components/interview-card/interview-card.component.html
  frontend/ATS/src/app/interviews/components/interview-card/interview-card.component.scss
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.html
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.scss
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.ts
  frontend/ATS/src/app/interviews/models/create-interview-dto.model.ts
  frontend/ATS/src/app/interviews/models/interview.model.ts
Labels: enhancement, UIchange

#247 Bug fix irina edit profile
  frontend/ATS/src/app/shared/components/header/header.component.html
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/app/shared/components/header/header.component.ts
  frontend/ATS/src/app/users/components/edit-hr-form/edit-hr-form.component.html
  frontend/ATS/src/app/users/components/edit-hr-form/edit-hr-form.component.ts
Labels: bug, UIchange

#256 bugfix
  backend/src/Application/Tasks/Commands/Update/UpdateTaskCommand.cs
  frontend/ATS/src/app/applicants/components/applicant-control/applicant-control.component.ts
  frontend/ATS/src/app/applicants/components/applicants/applicants.component.html
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.scss
  frontend/ATS/src/app/interviews/components/interviews-page/interviews-page.component.ts
  frontend/ATS/src/app/mail-templates/components/select-template-entities/select-template-entities.component.html
  frontend/ATS/src/app/users/components/forgot-password-dialog/forgot-password-dialog.component.scss
  frontend/ATS/src/app/users/components/hr-lead/send-registration-link-dialog/sending-register-link-dialog.component.scss
Labels: bug

#257 Fix for mail templates table and interview form
  backend/src/Application/Users/Queries/GetAllUsersInCompanyQuery.cs
  backend/src/Domain/Enums/MeetingSource.cs
  backend/src/WebAPI/Controllers/UsersController.cs
  backend/src/WebAPI/Extensions/WebHostExtenstions.cs
  frontend/ATS/src/app/interviews/components/create-interview/create-interview.component.html
  frontend/ATS/src/app/interviews/components/create-interview/create-interview.component.ts
  frontend/ATS/src/app/interviews/models/enums/meeting-source.enum.ts
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.html
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.scss
  frontend/ATS/src/app/mail-templates/components/mail-templates-list/mail-templates-list.component.ts
  frontend/ATS/src/app/users/services/user-data.service.ts
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.html
  frontend/ATS/src/app/vacancies/components/edit-vacancy/edit-vacancy.component.scss
  frontend/ATS/src/app/vacancies/components/stages/create-stage/create-stage.component.scss
Labels: bug

#259 Fix hide text in chips in task page
  frontend/ATS/src/app/shared/components/multiselect/multiselect.component.scss
  frontend/ATS/src/app/task-management/components/main-page/main-page.component.scss
  frontend/ATS/src/app/task-management/components/modal/all-in-one/all-in-one.component.scss
Labels: bug

#261 Ordered candidates
  backend/src/Application/Stages/StageProfile.cs
Labels: enhancement

#262 Added chrome extension download
  frontend/ATS/src/app/shared/components/header/header.component.html
  frontend/ATS/src/app/shared/components/header/header.component.scss
  frontend/ATS/src/assets/.gitkeep
  frontend/ATS/src/assets/chrome-extension.zip
  frontend/LinkedInScoutExtension/chrome/script.js
Labels: enhancement

#263 Fixed avatar showing on vacancy stages-candidates board
  frontend/ATS/src/app/shared/helpers/avatar.ts
  frontend/ATS/src/app/vacancies/components/vacancies-stages-board/vacancies-stages-board.component.ts
Labels: enhancement
